/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1ModelsRouteImport } from './routes/api/public/v1/models'
import { Route as ApiPublicV1ChatCompletionsRouteImport } from './routes/api/public/v1/chat/completions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ModelsRoute = ApiPublicV1ModelsRouteImport.update({
  id: '/api/public/v1/models',
  path: '/api/public/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ChatCompletionsRoute =
  ApiPublicV1ChatCompletionsRouteImport.update({
    id: '/api/public/v1/chat/completions',
    path: '/api/public/v1/chat/completions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/models': typeof ApiPublicV1ModelsRoute
  '/api/public/v1/chat/completions': typeof ApiPublicV1ChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/models': typeof ApiPublicV1ModelsRoute
  '/api/public/v1/chat/completions': typeof ApiPublicV1ChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/models': typeof ApiPublicV1ModelsRoute
  '/api/public/v1/chat/completions': typeof ApiPublicV1ChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/v1/models' | '/api/public/v1/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/v1/models' | '/api/public/v1/chat/completions'
  id:
    | '__root__'
    | '/'
    | '/api/public/v1/models'
    | '/api/public/v1/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1ModelsRoute: typeof ApiPublicV1ModelsRoute
  ApiPublicV1ChatCompletionsRoute: typeof ApiPublicV1ChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/models': {
      id: '/api/public/v1/models'
      path: '/api/public/v1/models'
      fullPath: '/api/public/v1/models'
      preLoaderRoute: typeof ApiPublicV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/chat/completions': {
      id: '/api/public/v1/chat/completions'
      path: '/api/public/v1/chat/completions'
      fullPath: '/api/public/v1/chat/completions'
      preLoaderRoute: typeof ApiPublicV1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1ModelsRoute: ApiPublicV1ModelsRoute,
  ApiPublicV1ChatCompletionsRoute: ApiPublicV1ChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
